language: c

compiler:
  - gcc
  - clang

env:
    - CONF="--disable-test-perf --disable-test-perf-proc"
    # - CONF="--disable-abi-compat --disable-test-perf --disable-test-perf-proc"
    # - CONF="--enable-schedule-sp"
    # - CONF="--enable-schedule-iquery"
    # - CONF="--enable-dpdk-zero-copy"
    # - CROSS_ARCH="arm64"
    # - CROSS_ARCH="armhf" CFLAGS="-march=armv7-a"
    # - CROSS_ARCH="powerpc"
    # - CROSS_ARCH="i386"

matrix:
  allow_failures:
    - compiler: clang
      env: CONF="--disable-abi-compat --disable-test-perf --disable-test-perf-proc"

build:
  pre_ci:
    # use Dockerfile to install additional CI dependencies
    - docker build -t=odp/dev ./scripts

  # use image built in 'pre_ci' for CI job
  pre_ci_boot:
    image_name: odp/dev
    image_tag: latest
    pull: false
    options:

  ci:
    - mkdir -p $HOME/odp-shmdir
    - ./bootstrap
    - if [ "${CC#clang}" != "${CC}" ] ; then export CXX="${CC/clang/clang++}"; fi
    - ./configure $CONF
    - make -j $(nproc)
    - sudo env CI=true ODP_SHM_DIR=$HOME/odp-shmdir ODP_TEST_OUT_XML=yes ODP_SCHEDULER=basic make check
    - ./scripts/shippable-post.sh basic
    - sudo env CI=true ODP_SHM_DIR=$HOME/odp-shmdir ODP_TEST_OUT_XML=yes ODP_SCHEDULER=sp make check
    - ./scripts/shippable-post.sh sp
    - sudo env CI=true ODP_SHM_DIR=$HOME/odp-shmdir ODP_TEST_OUT_XML=yes ODP_SCHEDULER=iquery make check
    - ./scripts/shippable-post.sh iquery
    - sudo env CI=true ODP_SHM_DIR=$HOME/odp-shmdir ODP_TEST_OUT_XML=yes ODP_SCHEDULER=scalable make check
    - ./scripts/shippable-post.sh scalable
    - rm -rf $HOME/odp-shmdir

  on_failure:
    - ./scripts/shippable-post.sh
    - cat config.log
    - find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done
