# Copyright (c) 2016, Linaro Limited
# All rights reserved.
# SPDX-License-Identifier:     BSD-3-Clause
#
# Please update xxxx for your coverity token and notification email if required
# pushing to github/master will run make check
# pushing to github/coverity_scan will also launch a static analysis
# See https://scan.coverity.com/travis_ci

language: c
sudo: required
dist: trusty
notifications:
  email: false
env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    # Note:
    # You should have a github account and travis linked travis account.
    # The secure key to be filled below is the 685 character long encrypted
    # token you can find as follow from your coverity dashboard
    # (at https://scan.coverity.com/dashboard):
    # Click on the github project (<you>/odp-dpdk)
    # Click on "submit build"
    # Click on "Configure Travis CI"
    # Look at the COVERITY_SCAN_TOKEN in the env: global: section
    # of the configuration example.
    # copy the secure:<key> below
    #
    - secure: "xxxx"
    #
    # By default Linaro CODECOV_TOKEN token is used. It's ok to use it to see
    # for individual commit validation. But you you want to track tests history
    # you need generated new one at https://codecov.io specific for your repo.
    - CODECOV_TOKEN=8e1c0fd8-62ff-411e-a79f-5839f6662c11

addons:
        apt:
                packages:
                        - gcc
                        - automake autoconf libtool graphviz mscgen doxygen
                        - codespell
                        - libssl-dev
                        - libpcap-dev
#        coverity_scan:
#                project:
#                        name: "$TRAVIS_REPO_SLUG"
#                        notification_email: xxxx
#                        build_command_prepend: "./bootstrap && ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-example"
#                        build_command:   "make"
#                        branch_pattern: coverity_scan

compiler:
        - gcc

cache:
        pip: true
        directories:
                - dpdk

env:
        - CONF=""
        - CONF="--disable-abi-compat"
        - CONF="--enable-schedule-sp"
        - CONF="--enable-schedule-iquery"

before_install:
#       Install cunit for the validation tests because distro version is too old and fails C99 compile
        - sudo apt-get remove libcunit1-dev libcunit1
        - wget http://ftp.debian.org/debian/pool/main/c/cunit/libcunit1_2.1-3-dfsg-2_amd64.deb
        - wget http://ftp.debian.org/debian/pool/main/c/cunit/libcunit1-dev_2.1-3-dfsg-2_amd64.deb
        - sudo dpkg -i libcunit1_2.1-3-dfsg-2_amd64.deb libcunit1-dev_2.1-3-dfsg-2_amd64.deb

install:
        - sudo apt-get -qq update
        - sudo apt-get install linux-headers-`uname -r`
        - gem install asciidoctor

        # DPDK. Note that cache must be purged if dpdk version changes.
        - DPDK_VERS="17.02"
        - |
          CACHED_DPDK_VERS=`fgrep Version dpdk/pkg/dpdk.spec | cut -d " " -f 2`
          if [ "${CACHED_DPDK_VERS}" != "${DPDK_VERS}" ]; then
            rm -rf dpdk
          fi
        - TARGET="x86_64-native-linuxapp-gcc"
        - DPDK_MACHINE=snb
        - |
          if [ -n "$TARGET" -a ! -f "dpdk/${TARGET}/lib/libdpdk.a" ]; then
            git -c advice.detachedHead=false clone -q --depth=1 --single-branch --branch=v${DPDK_VERS} http://dpdk.org/git/dpdk dpdk
            pushd dpdk
            git log --oneline --decorate
            echo $CC
            make config T=${TARGET} O=${TARGET}
            pushd ${TARGET}
            sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_PCAP=).*,\1y,' .config
            sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_OPENSSL=).*,\1y,' .config
            cat .config |grep RTE_MACHINE
            if test -n "${DPDK_MACHINE}" ; then
              sed -ri 's,(CONFIG_RTE_MACHINE=).*,\1"'${DPDK_MACHINE}'",' .config
            fi
            popd
            make install T=${TARGET} EXTRA_CFLAGS="-fPIC $DPDK_CFLAGS"
            rm -r ./doc ./${TARGET}/app ./${TARGET}/build
            popd
            EXTRA_CONF="$EXTRA_CONF --with-dpdk-path=`pwd`/dpdk/${TARGET}"
          fi

script:
        - ./bootstrap
        - ./configure --prefix=$HOME/odp-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-example --with-sdk-install-path=`pwd`/dpdk/${TARGET} $CONF
        - make -j $(nproc)
        - sudo LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" make check
        - make install

        # Wrapper-script.sh unmounts huge pages after make check
        - echo 1000 | sudo tee /proc/sys/vm/nr_hugepages
        - sudo mkdir -p /mnt/huge
        - sudo mount -t hugetlbfs nodev /mnt/huge

        - echo "Checking linking and run from install..."
        - pushd $HOME
        - echo "Dynamic link.."
        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst `PKG_CONFIG_PATH=${HOME}/odp-install/lib/pkgconfig pkg-config --cflags --libs libodp-dpdk`
        - sudo ODP_PLATFORM_PARAMS="-n 2" LD_LIBRARY_PATH="${HOME}/odp-install/lib:$LD_LIBRARY_PATH" ./odp_hello_inst
        - echo "Static link.."
        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst `PKG_CONFIG_PATH=${HOME}/odp-install/lib/pkgconfig pkg-config --cflags --libs libodp-dpdk --static` -static
        - sudo ODP_PLATFORM_PARAMS="-n 2" ./odp_hello_inst

jobs:
        include:
                - stage: test
                  env: TEST=coverage
                  compiler: gcc
                  script:
                          - sudo -H pip install coverage
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-example --with-sdk-install-path=`pwd`/dpdk/${TARGET} CFLAGS="-O0 -coverage" CXXFLAGS="-O0 -coverage" LDFLAGS="--coverage"
                          - sudo LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" PATH=${PATH//:\.\/node_modules\/\.bin/} make check
                          - find . -type f -iname '*.[ch]' -not -path ".git/*" -execdir gcov {} \; ; bash <(curl -s https://codecov.io/bash) -X coveragepy
                - stage: test
                  env: TEST=doxygen
                  compiler: gcc
                  script:
                          - ./bootstrap
                          - ./configure --with-sdk-install-path=`pwd`/dpdk/${TARGET}
                          # doxygen does not trap on warnings, check for them here.
                          - make doxygen-doc 2>&1 |tee doxygen.log
                          - |
                             fgrep -rq warning ./doxygen.log
                             if [ $? -eq 0 ]; then
                               false
                             else
                               true
                             fi
                - stage: test
                  env: TEST=checkpatch
                  compiler: gcc
                  install:
                          - true
                  script:
                          - echo ${TRAVIS_COMMIT_RANGE};
                          - ODP_PATCHES=`echo ${TRAVIS_COMMIT_RANGE} | sed 's/\.//'`;
                          - ./scripts/ci-checkpatches.sh ${ODP_PATCHES};

after_failure:
  - cat config.log
  - find . -name 'test-suite.log' -execdir grep -il "FAILED" {} \; -exec echo {} \; -exec cat {} \;
